/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.dutylist.api;

import org.dutylist.model.NewProduct;
import org.dutylist.model.Product;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

import java.util.List;


@Validated
@Tag(name = "Internal", description = "Endpoints that are called from other internal microservices")
public interface ProductsApi {

    /**
     * HEAD /products/{id} : Check a product exists
     *
     * @param id (required)
     * @return OK (status code 200)
     * or Bad Request (status code 400)
     * or Product not found (status code 404)
     */
    @Operation(
            operationId = "checkProduct",
            summary = "Check a product exists",
            description = "",
            tags = {"Internal"},
            responses = {
                    @ApiResponse(responseCode = "204", description = ""),
                    @ApiResponse(responseCode = "400", description = "Bad Request"),
                    @ApiResponse(responseCode = "404", description = "")
            }
    )
    @RequestMapping(
            method = RequestMethod.HEAD,
            value = "/products/{id}"
    )
    public ResponseEntity<Void> checkProduct(
            @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );


    /**
     * DELETE /products/{id} : Delete a product
     *
     * @param id     (required)
     * @param userId The user caller&#39;s ID (required)
     * @return (status code 204)
     * or Bad Request (status code 400)
     * or User ID is mandatory to access this resource (status code 401)
     * or You do not have permission to access this resource (status code 403)
     * or Product not found (status code 404)
     */
    @Operation(
            operationId = "deleteProduct",
            summary = "Delete a product",
            description = "",
            tags = {"Default"},
            responses = {
                    @ApiResponse(responseCode = "204", description = ""),
                    @ApiResponse(responseCode = "400", description = "Bad Request"),
                    @ApiResponse(responseCode = "401", description = "User ID is mandatory to access this resource"),
                    @ApiResponse(responseCode = "403", description = "You do not have permission to access this resource"),
                    @ApiResponse(responseCode = "404", description = "Product not found")
            }
    )
    @RequestMapping(
            method = RequestMethod.DELETE,
            value = "/products/{id}"
    )

    public ResponseEntity<Void> deleteProduct(
            @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id,
            @NotNull @Parameter(name = "user_id", description = "The user caller's ID", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "user_id", required = true) Integer userId
    );


    /**
     * GET /products/{id} : Retrieve a product
     *
     * @param id     (required)
     * @param userId The user caller&#39;s ID (required)
     * @return (status code 200)
     * or Bad Request (status code 400)
     * or User ID is mandatory to access this resource (status code 401)
     * or You do not have permission to access this resource (status code 403)
     * or Product not found (status code 404)
     */
    @Operation(
            operationId = "getProduct",
            summary = "Retrieve a product",
            description = "",
            tags = {"Default"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Product.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Bad Request"),
                    @ApiResponse(responseCode = "401", description = "User ID is mandatory to access this resource"),
                    @ApiResponse(responseCode = "403", description = "You do not have permission to access this resource"),
                    @ApiResponse(responseCode = "404", description = "Product not found")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/products/{id}",
            produces = {"application/json"}
    )

    public ResponseEntity<Product> getProduct(
            @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id,
            @NotNull @Parameter(name = "user_id", description = "The user caller's ID", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "user_id", required = true) Integer userId
    );


    /**
     * POST /products : Create a new product
     *
     * @param userId     The user caller&#39;s ID (required)
     * @param newProduct Request body for creating a new Product (optional)
     * @return (status code 200)
     * or Bad Request (status code 400)
     * or User ID is mandatory to access this resource (status code 401)
     */
    @Operation(
            operationId = "postProduct",
            summary = "Create a new product",
            description = "",
            tags = {"Default"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Product.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Bad Request"),
                    @ApiResponse(responseCode = "401", description = "User ID is mandatory to access this resource")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/products",
            produces = {"application/json"},
            consumes = {"application/json"}
    )

    public ResponseEntity<Product> postProduct(
            @NotNull @Parameter(name = "user_id", description = "The user caller's ID", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "user_id", required = true) Integer userId,
            @Parameter(name = "NewProduct", description = "Request body for creating a new Product") @Valid @RequestBody(required = false) NewProduct newProduct
    );


    /**
     * PUT /products/{id} : Update a product
     *
     * @param id         (required)
     * @param userId     The user caller&#39;s ID (required)
     * @param newProduct Request body for creating a new Product (optional)
     * @return (status code 200)
     * or Bad Request (status code 400)
     * or User ID is mandatory to access this resource (status code 401)
     * or You do not have permission to access this resource (status code 403)
     * or Product not found (status code 404)
     */
    @Operation(
            operationId = "putProduct",
            summary = "Update a product",
            description = "",
            tags = {"Default"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Product.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Bad Request"),
                    @ApiResponse(responseCode = "401", description = "User ID is mandatory to access this resource"),
                    @ApiResponse(responseCode = "403", description = "You do not have permission to access this resource"),
                    @ApiResponse(responseCode = "404", description = "Product not found")
            }
    )
    @RequestMapping(
            method = RequestMethod.PUT,
            value = "/products/{id}",
            produces = {"application/json"},
            consumes = {"application/json"}
    )

    public ResponseEntity<Product> putProduct(
            @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id,
            @NotNull @Parameter(name = "user_id", description = "The user caller's ID", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "user_id", required = true) Integer userId,
            @Parameter(name = "NewProduct", description = "Request body for creating a new Product") @Valid @RequestBody(required = false) NewProduct newProduct
    );


    /**
     * GET /products : Retrieves user&#39;s products
     *
     * @param userId The user caller&#39;s ID (required)
     * @return (status code 200)
     * or User ID is mandatory to access this resource (status code 401)
     * or You do not have permission to access this resource (status code 403)
     */
    @Operation(
            operationId = "searchProducts",
            summary = "Retrieves user's products",
            description = "",
            tags = {"Default"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "", content = {
                            @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Product.class)))
                    }),
                    @ApiResponse(responseCode = "401", description = "User ID is mandatory to access this resource"),
                    @ApiResponse(responseCode = "403", description = "You do not have permission to access this resource")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/products",
            produces = {"application/json"}
    )

    public ResponseEntity<List<Product>> searchProducts(
            @NotNull @Parameter(name = "user_id", description = "The user caller's ID", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "user_id", required = true) Integer userId,
            @Parameter(name = "name", description = "") @RequestParam(value = "name", required = false) String name
    );

}
